name: "Configure Kernel Options"
description: "Set up kernel configuration fragment with required options"
inputs:
  kernel_version:
    description: "Kernel version (e.g., 6.6)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply Kernel Configuration
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        cat "${{ github.workspace }}/.github/kernel-config/fragments/common.fragment" >> "${{ github.workspace }}/wild_gki.fragment"
      

    - name: Apply Kernel Config for 5.10
      shell: bash
      working-directory: ${{ github.workspace }}/kernel/common
      if: inputs.kernel_version == '5.10'
      run: |
        sed -i 's/CONFIG_IP_SET_MAX/65534/g' net/netfilter/ipset/ip_set_core.c
